# This is the main configuration file for the master_wrapper.py script.
#
# To run the script the $HCLIM_DIR environment variable must be defined and
# should point to a directory with simulations and postprocess folders:
#
# $HCLIM_DIR/
#   202201/
#   202202/
#   ...
#   postprocess/
#
# To run postprocessing for a simulation, configuration for the simulation
# must be specified in this file, and the `control_cmor.ini` located in
# the same folder as this file. `DataPath` must also be set explicitly
# in `control_cmor.ini` (replace [HCLIM_DIR] with the value of $HCLIM_DIR).
#
---
log_dir: "${HCLIM_DIR}/postprocess/HCLIM2CMOR/data/work/logs"

simulations:

  "202201":
    name_tag: "EUR11_EUR11_ALADIN43_v1_ERA5_r1i1p1f1_eval"
    gcm_name: "ECMWF-ERA5"
    experiment: "evaluation"
    start_year: 1980
    end_year: 2021
    var_list: "tas tasmax tasmin pr"

  "202202":
    name_tag: "EUR11_EUR11_ALADIN43_v1_CNRMESM21_r1i1p1f2_hist"
    gcm_name: "CNRM-ESM2-1"
    experiment: "historical"
    start_year: 1951
    end_year: 2014
    var_list: "tas tasmax tasmin pr"
